/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    alias(libs.plugins.moduleplugin)
    alias(libs.plugins.shadow)
    jacoco
}

group = "org.braid.society.secret"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()
}

dependencies {
    implementation(libs.bundles.annotations)
    implementation(libs.logback)

    // Use JUnit Jupiter for testing.
    testImplementation(libs.bundles.tests)
    testRuntimeOnly(libs.jupiter.engine)

    annotationProcessor(libs.bundles.annotations)
    testAnnotationProcessor(libs.bundles.annotations)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    finalizedBy("jacocoTestReport")
}

tasks.named<JacocoReport>("jacocoTestReport") {
    dependsOn("test")
    reports {
        xml.required.set(false)
        html.required.set(true)
    }
}
